CREATE TABLE checkin(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attendess_id VARCHAR(255) NOT NULL,
    CONSTRAINT checkin_attendess_id_fkey FOREIGN KEY (attendess_id) REFERENCES attendess (id) ON DELETE RESTRICT ON UPDATE CASCADE
);